### ISSUE TITLE
HOCON support does not work in version 0.2 and 0.3

### ISSUE THREAD

**Issue by ethanlu** [TrueDaerk/neo-config#1]
HOCON support works in version 0.1, but I get a HoconFormatException with a message of "Invalid key. Key may not contain new line character." in versions 0.2 and 0.3.

I get the error with a very simple configuration:

`
{
    myKey{
        value= 123
    }
}
`

This is on PHP 5.6.25 with mbstring module installed and enabled.

**Comment by TrueDaerk** [comment]
Fixed the issue, although the config did not throw a HoconFormatException in my case.
The parsing worked just fine, except that for this example the values read were
`{ "myKey{": { "value=": 123 } }`

I'm sorry it took so long, just did not log in for a while.
Will try to get to an issue faster next time.
